spring:
  datasource:
    url: jdbc:mysql://localhost:32306/user_center?useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.133:8848
        cluster-name: BJ
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        input:
          destination: stream-test-topic
          group: binder-group
        my-input:
          destination: stream-my-topic
          group: my-binder-group
  application:
    name: user-center
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080
rocketmq:
  name-server: localhost:9876