spring:
  datasource:
    url: jdbc:mysql://localhost:32306/content_center?useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.133:8848
        metadata: #设置实例级别的元数据
          file: file
          version: v1
        cluster-name: BJ
    sentinel:
      filter:
        enabled: false # 关闭对spring mvc 的保护
      transport:
        dashboard: localhost:8888
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        output:
          destination: stream-test-topic
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true
server:
  port: 8010
ribbon:
  user-center:
    enable: false
  globle:
    enable: true
  eager-load:
    enabled: true
logging:
  level:
    com.study.contentcenter.feign.UserCenterFeign: debug # 无论是否全局配置feign日志级别都需要这个配置
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
rocketmq:
  name-server: localhost:9876
  producer:
    group: test-group